### ISSUE TITLE
Premeditation not always working from true Stealth

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#764]
**Game Version:**
> 9.0.2 live Build 36753

**Description:**
> For some players and sometimes Premeditation does not trigger or extend any Slice and Dice when using Shadowstrike from true Stealth, despite properly having the Premeditation buff. No idea how to reproduce this, characters just seem to bug out randomly.
In my own case, it started when I entered Ardenweald while leveling to 60 and turned off Warmode. Since then it has stopped working in any world content but it does work in dungeons for me.

**Comment by Mystler** [comment]
Closing this as it should be fixed in 9.0.5 and I haven't had or heard of remaining issues with it.

**Comment by Helliox** [comment]
The bug still exists. I'm leveling a rogue now and the SnD buff is applied randomly. Was working 100% of the time on stormwind dummies though. Weird.
